/**
 * API client for the three backend services.
 *
 * Every request goes through one function so that authentication, error
 * shaping and token refresh exist in exactly one place. The base URL comes
 * from the environment file generated by bin/generate-env.sh -- it is never
 * hardcoded, because it differs between LocalStack and AWS.
 */

const BASE = import.meta.env.VITE_API_URL || 'http://localhost:3001';

const AUTH = `${BASE}/api/auth-service`;
const PROJ = `${BASE}/api/project-service`;
const ANLY = `${BASE}/api/analytics-service`;

const TOKEN_KEY = 'acme.access_token';
const REFRESH_KEY = 'acme.refresh_token';
const USER_KEY = 'acme.user';

export const tokens = {
  get access() { return sessionStorage.getItem(TOKEN_KEY); },
  get refresh() { return sessionStorage.getItem(REFRESH_KEY); },
  get user() {
    const raw = sessionStorage.getItem(USER_KEY);
    return raw ? JSON.parse(raw) : null;
  },
  set({ access_token, refresh_token, user }) {
    if (access_token) sessionStorage.setItem(TOKEN_KEY, access_token);
    if (refresh_token) sessionStorage.setItem(REFRESH_KEY, refresh_token);
    if (user) sessionStorage.setItem(USER_KEY, JSON.stringify(user));
  },
  clear() {
    [TOKEN_KEY, REFRESH_KEY, USER_KEY].forEach((k) => sessionStorage.removeItem(k));
  },
};

/** An API failure that carries the server's status code and field details. */
export class ApiError extends Error {
  constructor(status, message, details) {
    super(message);
    this.status = status;
    this.details = details || [];
  }
}

async function parse(response) {
  if (response.status === 204) return null;
  const text = await response.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    // A non-JSON body means the Lambda crashed before our handler ran.
    throw new ApiError(response.status, 'The server returned an unexpected response');
  }
}

async function request(url, { method = 'GET', body, retry = true } = {}) {
  let response;
  try {
    response = await fetch(url, {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...(tokens.access ? { Authorization: `Bearer ${tokens.access}` } : {}),
      },
      ...(body ? { body: JSON.stringify(body) } : {}),
    });
  } catch {
    throw new ApiError(0, 'Cannot reach the server. Check that the backend is running.');
  }

  // An expired access token is recoverable: refresh once, then replay.
  if (response.status === 401 && retry && tokens.refresh && !url.endsWith('/login')) {
    const refreshed = await tryRefresh();
    if (refreshed) return request(url, { method, body, retry: false });
  }

  const data = await parse(response);

  if (!response.ok) {
    throw new ApiError(
      response.status,
      data?.error || `Request failed (${response.status})`,
      data?.details,
    );
  }
  return data;
}

async function tryRefresh() {
  try {
    const response = await fetch(`${AUTH}/refresh`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${tokens.refresh}` },
    });
    if (!response.ok) return false;
    const data = await response.json();
    tokens.set({ access_token: data.access_token });
    return true;
  } catch {
    return false;
  }
}

const qs = (params = {}) => {
  const clean = Object.entries(params).filter(([, v]) => v !== '' && v != null);
  return clean.length ? `?${new URLSearchParams(clean)}` : '';
};

// -------------------------------------------------------------------------
// Auth
// -------------------------------------------------------------------------

export const login = async (email, password) => {
  const data = await request(`${AUTH}/login`, { method: 'POST', body: { email, password } });
  tokens.set(data);
  return data;
};

export const logout = () => tokens.clear();

// Public: creates a read-only account. The server ignores any role sent here.
export const register = (body) => request(`${AUTH}/register`, { method: 'POST', body });
export const forgotPassword = (email) =>
  request(`${AUTH}/forgot-password`, { method: 'POST', body: { email } });
export const resetPassword = (token, password) =>
  request(`${AUTH}/reset-password`, { method: 'POST', body: { token, password } });

export const getMe = () => request(`${AUTH}/me`);
export const getUsers = (params) => request(`${AUTH}/users${qs(params)}`);
export const createUser = (body) => request(`${AUTH}/users`, { method: 'POST', body });
export const updateUser = (id, body) => request(`${AUTH}/users/${id}`, { method: 'PUT', body });
export const deleteUser = (id) => request(`${AUTH}/users/${id}`, { method: 'DELETE' });

// -------------------------------------------------------------------------
// Projects and deliverables
// -------------------------------------------------------------------------

export const getDashboard = () => request(`${PROJ}/dashboard`);
export const getProjects = (params) => request(`${PROJ}/projects${qs(params)}`);
export const getProject = (id) => request(`${PROJ}/projects/${id}`);
export const createProject = (body) => request(`${PROJ}/projects`, { method: 'POST', body });
export const updateProject = (id, body) => request(`${PROJ}/projects/${id}`, { method: 'PUT', body });
export const deleteProject = (id) => request(`${PROJ}/projects/${id}`, { method: 'DELETE' });

export const getDeliverables = (params) => request(`${PROJ}/deliverables${qs(params)}`);
export const createDeliverable = (body) => request(`${PROJ}/deliverables`, { method: 'POST', body });
export const updateDeliverable = (id, body) => request(`${PROJ}/deliverables/${id}`, { method: 'PUT', body });
export const deleteDeliverable = (id) => request(`${PROJ}/deliverables/${id}`, { method: 'DELETE' });

export const getDependencies = (params) => request(`${PROJ}/dependencies${qs(params)}`);
export const createDependency = (body) => request(`${PROJ}/dependencies`, { method: 'POST', body });
export const deleteDependency = (body) => request(`${PROJ}/dependencies`, { method: 'DELETE', body });

export const getAllocations = (params) => request(`${PROJ}/allocations${qs(params)}`);
export const createAllocation = (body) => request(`${PROJ}/allocations`, { method: 'POST', body });
export const deleteAllocation = (id) => request(`${PROJ}/allocations/${id}`, { method: 'DELETE' });

export const getBudget = (params) => request(`${PROJ}/budget${qs(params)}`);
export const createExpense = (body) => request(`${PROJ}/expenses`, { method: 'POST', body });
export const getDepartments = () => request(`${PROJ}/departments`);

// -------------------------------------------------------------------------
// Analytics
// -------------------------------------------------------------------------

export const getPortfolio = () => request(`${ANLY}/portfolio`);
export const getForecast = () => request(`${ANLY}/forecast`);
export const getScores = () => request(`${ANLY}/scores`);
export const getInsights = () => request(`${ANLY}/insights`);
export const getAudit = (params) => request(`${ANLY}/audit${qs(params)}`);
export const refreshPortfolio = () => request(`${ANLY}/refresh`, { method: 'POST' });
